### ISSUE TITLE
Authenticate Issue

### ISSUE THREAD

**Issue by Feuerforst** [floblik/YouScrobbler#12]
Hey,

i have a new Bug/Issue.

I`m not sure how to reproduce it but sometimes i got an Error Popup, but it show no error message. 
After that scrobbling is not working.

So i deinstalled the Script and restartet FF.
After that i installed it again and try to login, but it`s not working.
"Error: Error occured while connecting to Last.FM Api"

Sometimes it`s working when i delete the Last.fm Cookies but at the Moment it`s not.

deleteing last.fm Cookies - not working
reinstall Script/Plugin - not working.

Firefox 51.0.1 (64-Bit)
Greasemonkey 3.10
YouScrobbler 1.4.2

**Comment by floblik** [comment]
Hey,

I'm able to authenticate without problems.
I added some logging server side. Maybe that helps investigating the problem.

So please try it a few times more and tell me if the problem persists.

**Comment by Feuerforst** [comment]
after few Minutes i could also authenticate without Problems.
But now i have again the other Problem

i try to watch a Video and everthing looks normal:
![img_002](https://cloud.githubusercontent.com/assets/26187902/23705468/44a1097e-040a-11e7-9835-3c8b66a09082.jpg)
The Timer is running normal:
![img_003](https://cloud.githubusercontent.com/assets/26187902/23705471/4819d9aa-040a-11e7-870e-10cf2f9d056f.jpg)

But than this message pops up:
![img_004](https://cloud.githubusercontent.com/assets/26187902/23705473/4a360010-040a-11e7-9ed3-a53ebb219883.jpg)

and if i pres manual the Scrobble Button i can see this:
![img_005](https://cloud.githubusercontent.com/assets/26187902/23705477/4c71074e-040a-11e7-8f78-4b35d01989cf.jpg)

**Comment by Feuerforst** [comment]
And now i hit the Reset Auth Button i can`t login again

![img_002](https://cloud.githubusercontent.com/assets/26187902/23705770/a081d8e4-040b-11e7-892e-1b1d6536b734.jpg)

![img_002](https://cloud.githubusercontent.com/assets/26187902/23705759/991400a0-040b-11e7-9093-3cbc627ce26c.jpg)

**Comment by Feuerforst** [comment]
And now i hit the Reset Auth Button and can`t login
![img_003](https://cloud.githubusercontent.com/assets/26187902/23705787/ba6b5e6a-040b-11e7-9c37-37fbdf729805.jpg)
![img_002](https://cloud.githubusercontent.com/assets/26187902/23705791/bd150c88-040b-11e7-9392-7a15859bf1ed.jpg)

**Comment by floblik** [comment]
Can you check it now again?
I had some similar problems but seems its fixed now.

**Comment by rururux** [comment]
i have same problem
still showing error("Error occured while connecting to Last.FM Api") in 1.4.3

Firefox 52.0 64bit

**Comment by Feuerforst** [comment]
Thx.

i`m trying. But at the Moment i don`t know how i can reproduce this Error.

I used the Reset Auth Button and with 1.4.3 i could Login back without Problems.

**Comment by Feuerforst** [comment]
Ok Problem is still there.
This Error popped up and if i reseth the Auth i can`t login again.

**Comment by rururux** [comment]
oh?
now i was able to log in.

**Comment by Feuerforst** [comment]
Even after many hours i cannot Authenticate. 
tryed to delete the Cookies.
reseted many times the Auth
restarded the Browser many times

**Comment by floblik** [comment]
What about 1.4.4 ?

**Comment by rururux** [comment]
1.4.4, Succesfully logged in :)
thank you

**Comment by nikolettk** [comment]
Hi, I have the same problem with the same error messages. I had it about two weeks ago, then I installed the 1.4.4. version as you suggested here, which solved the issue, however the errors appeared again today. After getting the "could not connect to last fm API", I reset my login, but cannot even authenticate, as it says "error occurred while connecting to last fm API". I am using Mozilla Firefox 52.0.1 (32 bit).

Edit: some days it works (for a while), other days it doesn't.

**Comment by duri2** [comment]
Same story here, unfortunately (Firefox 52.0.1 64-bit)

**Edit:**  Everything seems working fine, maybe it was a problem on Last.fm side.

**Comment by Ravanger** [comment]
I can confirm this new strange behaviour. Sometimes it works perfectly, other days it won't let me scrobble or authenticate with the same error as above.

**Comment by Feuerforst** [comment]
it looks that it happens when youtube switches the SOng with autoplay and when the new Song start you can see the green Message in the Corner and the Timer starts so run down. 
In this Moment, when the Timer is running down and you switch the Song, ne new message comes up and says scrobbling in X Sek and at this moment its broken and no Songs can`t be scrobbled

**Comment by floblik** [comment]
@Feuerforst As I read your comment I was using YouScrobbler and got the error on a track I was listening. I kept refreshing the YouTube page and getting the error. After about 10 - 15 min it worked again and I could keep listening to Autoplay tracks.


And as above said
> I can confirm this new strange behaviour. Sometimes it works perfectly, other days it won't let me scrobble or authenticate with the same error as above.

This may be caused by many repeatedly made requests. Heres an excerpt of a log file from today on youscrobbler api server: 
![grafik](https://cloud.githubusercontent.com/assets/8873992/25046344/3ac4da36-2131-11e7-81d4-c21926566d63.png)

And 7 minutes later still:

![grafik](https://cloud.githubusercontent.com/assets/8873992/25046369/600aaffa-2131-11e7-9b72-f4441ae7f213.png)

As you can see the requests are beeing blocked but still may run the server to capacity.

**Comment by duri2** [comment]
Maybe there should be an option to use own Last.fm API key? It's possible to create one: https://www.last.fm/api/account/create

**Comment by halfh07** [comment]
I have the same problem with firefox 59.0.1 (64 bits) and YouScrobbler 1.4.7 with tampermonkey 4.6.5709

every time y tray to authenticate it sends me to last.fm and then back to youtube and ask for authentication again
